CW9/Models/AdCreateModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CW9.Models
{
    public class AdCreateModel
    {
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Content")]
        public string Content { get; set; }
        
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        public SelectList CategoriesSelect { get; set; }
        
        [Required]
        [Display(Name = "Contact")]
        public string OwnerContact { get; set; }
        
        [Required]
        [Display(Name = "Price")]
        public int Price { get; set; }
        
        [Display(Name = "Main image")]
        public IFormFile Image { get; set; }
        
        [Display(Name = "Image gallery")]
        public IFormFileCollection Images { get; set; }
    }
}

CW9/Models/AdEditModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CW9.Models
{
    public class AdEditModel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Content")]
        public string Content { get; set; }
        
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        public SelectList CategoriesSelect { get; set; }
        
        [Required]
        [Display(Name = "Contact")]
        public string OwnerContact { get; set; }
        
        [Required]
        [Display(Name = "Price")]
        public int Price { get; set; }
        
        [Display(Name = "Main image")]
        public IFormFile Image { get; set; }
        
        [Display(Name = "Image gallery")]
        public IFormFileCollection Images { get; set; }
    }
}

CW9/Models/AdIndexModel.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CW9.Models
{
    public class AdIndexModel
    {
        public string SearchKey { get; set; }
        public string Category { get; set; }
        public int? PriceFrom { get; set; }
        public int? PriceTo { get; set; }
        public bool HasImage { get;  set; }
        public List<AdModel> Ads { get; set; }
        public int? Page { get; set; }
    }
}

CW9/Models/AdModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CW9.DAL.Entities;

namespace CW9.Models
{
    public class AdModel
    {
        public int Id { get; set; }
        public string DatePublished { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Price { get; set; }
        public string OwnerContact { get; set; }
        public string OwnerName { get; set; }
        public string Category { get; set; }
        public DateTime Upped { get; set; }
        public byte[] Image { get; set; }
        public List<Image> Images { get; set; }
    }
}

CW9/Models/ErrorViewModel.cs
using System;

namespace CW9.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CW9/Controllers/AdController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using CW9.DAL.Entities;
using CW9.Models;
using CW9.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CW9.Controllers
{
    public class AdController: Controller
    {
        private readonly IAdService _adService;
        private readonly UserManager<User> _userManager;

        public AdController(IAdService adService, UserManager<User> userManager)
        {
            _adService = adService;
            _userManager = userManager;
        }
        
        public IActionResult Index(AdIndexModel model)
        {
            try
            {
                var adModels = _adService.GetAllAds(model);
                
                model.Ads = adModels;

                return View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [Authorize]
        public IActionResult Create()
        {
            var model = _adService.GetAdCreateModel();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateAd(AdCreateModel model)
        {
            try
            {
                User currentUser = await _userManager.GetUserAsync(User);

                 _adService.CreateAd(model, currentUser.Id);

                 return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int adId)
        {
            var adModel = _adService.GetById(adId);

            return View(adModel);
        }
        
        [Route("Edit/{id?}")]
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                ViewBag.BadRequestMessage = "Product id cannot be NULL";
                return View("Error");
            }

            var adEditModel = _adService.GetAdById(id.Value);

            return View(adEditModel);
        }

        [HttpPost]
        public IActionResult EditProduct(AdEditModel model)
        {
            try
            {
                _adService.EditAd(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
        
        
        [Authorize]
        [HttpPost]
        public IActionResult UpAjax(int adId)
        {
            try
            {
                _adService.UpAd(adId);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }
    }
}

CW9/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CW9.Models;

namespace CW9.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

CW9/Views/Ad/Create.cshtml
@model AdCreateModel

@{
    ViewBag.Title = "MyLalafo: Add new ad";
    Layout = "_Layout";
}

<h2>Create ad</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAd" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerContact" class="control-label"></label>
                <input asp-for="OwnerContact" class="form-control" />
                <span asp-validation-for="OwnerContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="@Model.CategoriesSelect"></select>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" accept="image/*" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Images" class="control-label"></label>
                <input asp-for="Images" type="file" multiple="multiple" accept="image/*" class="form-control" />
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CW9/Views/Ad/Details.cshtml
@model AdModel

@{
    ViewData["Title"] = "MyLalafo: " + Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
	
}
<style>
	.gallery-wrap .img-big-wrap img {
        height: 450px;
        width: auto;
        display: inline-block;
    }
    .img-small-wrap img {
        height: 450px;
        width: auto;
        display: inline-block;
    }
    
</style>
<div>
	<input type="button" adId="@Model.Id" class="btn-primary" id = "UpAd" value="UP"/>
	@* <a class="mt-0 font-weight-bold mb-2" asp-action="Edit" asp-route-Id="@Model.Id">Edit</a> *@
</div>
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
			<article class="gallery-wrap"> 
				<div class="img-big-wrap">
					<div> <a href="#"><img width="500" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))"/></a></div>
				</div>
			</article>
		</aside>
		<aside class="col-sm-7">
			<article class="card-body p-5">
				<h3 class="title mb-3">@Model.Title</h3>
				<p class="price-detail-wrap">
				<span class="price h3 text-warning">
					<span class="currency">US $</span><span class="num">@Model.Price</span>
				</span>
				<dl class="item-property">
					<dt>Description</dt>
					<dd>
						<p>@Model.Content</p>
					</dd>
				</dl>
				<dl class="param param-feature">
					<dt>Category</dt>
					<dd>@Model.Category</dd>
				</dl> 
				<dl class="param param-feature">
					<dt>Contact</dt>
					<dd>@Model.OwnerContact</dd>
				</dl> 
				<dl class="param param-feature">
					<dt>Owner name</dt>
					<dd>@Model.OwnerName</dd>
				</dl> 
			</article>
		</aside> 
	</div> 
</div>
<hr>
<article>
	<div class="img-small-wrap raw">
		@foreach (var image in Model.Images)
		{
			if (image.ImageBytes != null && image.ImageBytes.Length > 0)
			{
				<div class="item-gallery"><img src="data:image/jpeg;base64,@(Convert.ToBase64String(image.ImageBytes))"/></div>
			}
		}
	</div>
</article>

<script >
$(document).ready(function() {
	$('#UpAd').on('click',
	function() {
		alert('link');
        var AdId = $(this).attr('AdId');
        $.ajax({
          method: 'GET',
          url: '@Url.Action("UpAjax", "Ad")' + '?adId=' + AdId,
          success: function (data) {
          console.log(data);
          $('body').html(data);
          }
        });
	});
});
</script>

CW9/Views/Ad/Edit.cshtml
@model CW9.DAL.Entities.Ad

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Edit ad</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAd" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" value="@Model.Id" />
            <input asp-for="Category" type="hidden" value="@Model.CategoryId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerContact" class="control-label"></label>
                <input asp-for="OwnerContact" class="form-control" />
                <span asp-validation-for="OwnerContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            @* <div class="form-group"> *@
            @*     <label asp-for="CategoryId" class="control-label"></label> *@
            @*     <select asp-for="CategoryId" class="form-control" asp-items="@Model.CategoriesSelect"></select> *@
            @* </div> *@
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" accept="image/*" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Images" class="control-label"></label>
                <input asp-for="Images" type="file" multiple="multiple" accept="image/*" class="form-control" />
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CW9/Views/Ad/Index.cshtml
@model AdIndexModel

@{
    ViewBag.Title = "MyLalafo: All ads";
    Layout = "_Layout";
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    <div class="col-lg-12">
        <form asp-action="Index" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Page" value="@Model.Page" />
            <div class="form-group col-lg-12">
                <label asp-for="SearchKey" class="control-label">Search key</label>
                <input asp-for="SearchKey" class="form-control" value="@Model.SearchKey" />
                <span asp-validation-for="SearchKey" class="text-danger"></span>
            </div>
            <div class="col-lg-3">
                <label asp-for="PriceFrom" class="control-label">Price from</label>
                <input asp-for="PriceFrom" class="form-control" value="@Model.PriceFrom" />
                <span asp-validation-for="PriceFrom" class="text-danger"></span>
            </div>
            <div class="col-lg-3">
                <label asp-for="PriceTo" class="control-label">Price to</label>
                <input asp-for="PriceTo" class="form-control" value="@Model.PriceTo"/>
                <span asp-validation-for="PriceTo" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-3">
                <label asp-for="Category" class="control-label">Category </label>
                <input asp-for="Category" class="form-control" value="@Model.Category"></input>
            </div>
            <div class="form-group col-lg-3">
                <label asp-for="HasImage" class="control-label">With image</label>
                <input asp-for="HasImage" class="form-control" checked="@Model.HasImage" />
                <span asp-validation-for="HasImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<partial name="_AdsPartial" model="@Model" />

CW9/Views/Ad/_AdsPartial.cshtml
@model AdIndexModel

<div class="row">
    <div class="col-lg-8 mx-auto">
        <ul class="list-group shadow">
             @foreach (var item in Model.Ads)
             {
                  <li class="list-group-item">
                      <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                          <div class="media-body order-2 order-lg-1">
                              <a class="mt-0 font-weight-bold mb-2" asp-action="Details" asp-route-adId="@item.Id">
                                  @Html.DisplayFor(modelItem => item.Title)
                              </a>
                              <p class="font-italic text-muted mb-0 small">@Html.DisplayFor(modelItem => item.Content)</p>
                              <div class="d-flex align-items-center justify-content-between mt-1">
                                  <h6 class="font-weight-bold my-2">Price : @Html.DisplayFor(modelItem => item.Price)$</h6>
                                  <ul class="list-inline small">
                                      Category: @Html.DisplayFor(modelItem => item.Category)
                                  </ul>
                              </div>
                          </div>
                          @if(item.Image.Length > 0){
                              <img src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Image))" alt="Generic placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
                          }
                          else
                          {
                              <img src="default-no-image.png" width="200" class="ml-lg-5 order-1 order-lg-2">
                          }
                          
                      </div>
                  </li>
             }
        </ul> 
    </div>
</div>

CW9/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CW9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CW9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyLalafo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Ad" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - CW9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>